# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-ppe-middleware"
BBFILE_PATTERN_meta-ppe-middleware = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-ppe-middleware = "6"

LAYERDEPENDS_meta-ppe-middleware = "core"
LAYERSERIES_COMPAT_meta-ppe-middleware = "scarthgap"
