# Kế thừa policy của poky rồi override tối thiểu
require conf/distro/poky.conf

DISTRO          = "ppe-lite"
DISTRO_NAME     = "PPE Lite Distro"
DISTRO_VERSION  = "0.1"

# Providers & init (đủ cho test dịch vụ, mạng)
INIT_MANAGER = "systemd"
VIRTUAL-RUNTIME_init_manager        = "systemd"
VIRTUAL-RUNTIME_dev_manager         = "udev"
VIRTUAL-RUNTIME_login_manager       = "shadow-base"
VIRTUAL-RUNTIME_base-utils          = "busybox"
VIRTUAL-RUNTIME_base-utils-syslog   = "busybox-syslog"

# Định dạng gói & tính năng
PACKAGE_CLASSES = "package_ipk"
DISTRO_FEATURES:append = " systemd ipv4 ipv6 "
DISTRO_FEATURES:remove = " x11 "

# Artifact mặc định
IMAGE_FSTYPES ?= "wic.gz"

# Thống kê build (hữu ích cho báo cáo)
INHERIT += "buildstats buildhistory"
BUILDHISTORY_COMMIT = "1"
